cursor            #81d3de
cursor_text_color #00363c

foreground            #dee4e4
background            #090f10
selection_foreground  #1c3437
selection_background  #b1cbcf
url_color             #b1cbcf

#: black 000000 767676
color0  #0e1415
color8  #303637
#: red cc0403 f2201f
color1  #ffffff
color9  #2ac5f1
#: green 19cb00 23fd00
color2  #b1cbcf
color10 #051f22
#: yellow cecb00 fffd00
color3  #81d3de
color11 #001f23
#: blue 0d73cc 1a8fff
color4  #81d3de
color12 #00363c
#: magenta cb1ed1 fd28ff
color5  #b1cbcf
color13 #1c3437
#: cyan 0dcdcd 14ffff
color6  #81d3de
color14 #00363c
#: white dddddd ffffff
color7  #bec8ca
color15 #dee4e4

mark1_foreground #001f23
mark1_background #9df0fb
mark2_foreground #051f22
mark2_background #cde7eb
mark3_foreground #0c1b36
mark3_background #d8e2ff

active_tab_foreground #00363c
active_tab_background #81d3de
inactive_tab_foreground #9df0fb
inactive_tab_background #004f56

active_border_color #81d3de
inactive_border_color #00363c
# bell_border_color #ff5a00
