$image = /home/sid/.config/wallpapers/wall20.png

$background = rgba(12140dff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2f3129ff)

$inverse_primary = rgba(526526ff)

$inverse_surface = rgba(e3e3d7ff)

$on_background = rgba(e3e3d7ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(263500ff)

$on_primary_container = rgba(d4ec9dff)

$on_primary_fixed = rgba(151f00ff)

$on_primary_fixed_variant = rgba(3b4d0fff)

$on_secondary = rgba(2c331cff)

$on_secondary_container = rgba(dee6c5ff)

$on_secondary_fixed = rgba(181e09ff)

$on_secondary_fixed_variant = rgba(424a31ff)

$on_surface = rgba(e3e3d7ff)

$on_surface_variant = rgba(c6c8b8ff)

$on_tertiary = rgba(023732ff)

$on_tertiary_container = rgba(bcece3ff)

$on_tertiary_fixed = rgba(00201cff)

$on_tertiary_fixed_variant = rgba(204e48ff)

$outline = rgba(909284ff)

$outline_variant = rgba(45483cff)

$primary = rgba(b9cf84ff)

$primary_container = rgba(3b4d0fff)

$primary_fixed = rgba(d4ec9dff)

$primary_fixed_dim = rgba(b9cf84ff)

$scrim = rgba(000000ff)

$secondary = rgba(c2caaaff)

$secondary_container = rgba(424a31ff)

$secondary_fixed = rgba(dee6c5ff)

$secondary_fixed_dim = rgba(c2caaaff)

$shadow = rgba(000000ff)

$source_color = rgba(d8d8cdff)

$surface = rgba(12140dff)

$surface_bright = rgba(383a32ff)

$surface_container = rgba(1f2019ff)

$surface_container_high = rgba(292b23ff)

$surface_container_highest = rgba(34362eff)

$surface_container_low = rgba(1b1c15ff)

$surface_container_lowest = rgba(0d0f08ff)

$surface_dim = rgba(12140dff)

$surface_tint = rgba(b9cf84ff)

$surface_variant = rgba(45483cff)

$tertiary = rgba(a1d0c7ff)

$tertiary_container = rgba(204e48ff)

$tertiary_fixed = rgba(bcece3ff)

$tertiary_fixed_dim = rgba(a1d0c7ff)

