cursor            #dcc66e
cursor_text_color #3a3000

foreground            #e9e2d4
background            #100e07
selection_foreground  #373016
selection_background  #d2c6a1
url_color             #d2c6a1

#: black 000000 767676
color0  #16130b
color8  #38352b
#: red cc0403 f2201f
color1  #ffffff
color9  #cda74f
#: green 19cb00 23fd00
color2  #d2c6a1
color10 #211b04
#: yellow cecb00 fffd00
color3  #dcc66e
color11 #221b00
#: blue 0d73cc 1a8fff
color4  #dcc66e
color12 #3a3000
#: magenta cb1ed1 fd28ff
color5  #d2c6a1
color13 #373016
#: cyan 0dcdcd 14ffff
color6  #dcc66e
color14 #3a3000
#: white dddddd ffffff
color7  #cdc6b4
color15 #e9e2d4

mark1_foreground #221b00
mark1_background #f9e287
mark2_foreground #211b04
mark2_background #eee2bc
mark3_foreground #00210f
mark3_background #c5eccd

active_tab_foreground #3a3000
active_tab_background #dcc66e
inactive_tab_foreground #f9e287
inactive_tab_background #544600

active_border_color #dcc66e
inactive_border_color #3a3000
# bell_border_color #ff5a00
